### ISSUE TITLE
Show prices with Monero results in 0.000000000 XMR and also can't checkout.

### ISSUE THREAD

**Issue by HeatherThomsen** [monero-integrations/monerowp#100]
I have tried everything:
Setting MySQL permssions to 3306
Installed Curl and Json
Restarted nginx countless times
What should I do now?

**Comment by serhack** [comment]
Thanks for having filled an issue for MoneroWP Project. I have a few questions for you: have you enabled WP_DEBUG? Have you looked for Woocommerce Logs? Is Coingecko API reachable from Wordpress?

Would you please also specify the version of Wordpress, Woocommerce, and PHP?

**Comment by HeatherThomsen** [comment]
Wordpress = 5.7.2
Woocommerce = Latest
Php 7.3 with bcmath,json,curl,fpm,mysql running on ubuntu 20.04

I enabled debug and discovered the errors:

Notice: Trying to get property 'rate' of non-object in /var/www/html/wp-content/plugins/monero-woocommerce-gateway/include/class-monero-gateway.php on line 774

and

Warning: Division by zero in /var/www/html/wp-content/plugins/monero-woocommerce-gateway/include/class-monero-gateway.php on line 721

**Comment by absolutez3** [comment]
I am also experiencing this on CentOS 8, same exact error as above.

**Comment by absolutez3** [comment]
Solved for me, it was a cron issue.

**Comment by coffeeguy999** [comment]
> Solved for me, it was a cron issue.

can you elaborate?
