### ISSUE TITLE
Set Order Status to "Processing" Rather than "Completed" When Payment Received

### ISSUE THREAD

**Issue by mathys-lab** [monero-integrations/monerowp#111]
Currently, the Woocommerce Order Status is updated to Completed when the payment is received. Is there any way we can change this to "Processing" rather than "Competed"?

**Comment by BrianHenryIE** [comment]
Replace these lines:

https://github.com/monero-integrations/monerowp/blob/9ba2b640f7bd31441f9994dd66916bf480ed9016/include/class-monero-gateway.php#L395-L399

With:

`$order->payment_complete();`

WooCommerce takes care of conditionally setting the order status to `processing` or `complete` so this plugin shouldn't be bothering to do that too. See: [class-wc-order.php](https://github.com/woocommerce/woocommerce/blob/76824d336537b0b6d95017ee5a220ede7637bc88/plugins/woocommerce/includes/class-wc-order.php#L142)

**Comment by mathys-lab** [comment]
Thank you. I also noticed that my issue was that my test product is virtual only which causes it to return as "completed". Everything is working as expected. Thank you!
