### ISSUE TITLE
Order Price Changes As Page Refreshes 

### ISSUE THREAD

**Issue by Alicesland** [monero-integrations/monerowp#28]
The Monero amount of the order isn't set in stone when order is created but instead calculated and updated on every page refresh. This leads to discrepancies when an individual pays and the amount it's looking for. Especially when there is high volatility on the price.  

Ideally the amount of xmr would be set on the order creation and not updated on every refresh.

**Comment by serhack** [comment]
Okay, @cryptochangements34 we should decrease the value of cookie for payment ..

**Comment by serhack** [comment]
The price is very volatile. The price will be stable for 30 minutes and after then it will re-scan for price exchange.

Please let me know about questions
