### ISSUE TITLE
Payment verifications seems wrong

### ISSUE THREAD

**Issue by fabiomsouto** [monero-integrations/monerowp#31]
Hello there,

https://github.com/monero-integrations/monerowp/blob/2140291ce820673d0cb9b76da76f9e7838b4aa24/monero/include/monero_payments.php#L399

To pay 1XMR, If I issue two payments of .5XMR instead of a single 1XMR payment, this check will fail, but I still paid in full. So this verification will fail for some cases. Just wanted to give you a heads up, might be of interest to improve the check.

Cheers.

**Comment by serhack** [comment]
Hello,
serhack here.

Yes, that is an issue: our plugin can't support two transaction for the same amount. 
We will think about a solution with subaddresses, maybe. Consider: more transactions, more errors if one is wrong.

**Comment by cryptochangements34** [comment]
@fabiomsouto Thanks for pointing this out. It should now be fixed in PR #35
