### ISSUE TITLE
SQL Injection in monero_payments.php.

### ISSUE THREAD

**Issue by gerry** [monero-integrations/monerowp#32]
Hey,

It seems monero_payments.php is vulnerable to a SQL injection via `$payment_id`. 

[monero_payments.php#L319](https://github.com/monero-integrations/monerowp/blob/2140291ce820673d0cb9b76da76f9e7838b4aa24/monero/include/monero_payments.php#L319)
[monero_payments.php#L331](
https://github.com/monero-integrations/monerowp/blob/2140291ce820673d0cb9b76da76f9e7838b4aa24/monero/include/monero_payments.php#L331)
[monero_payments.php#L334](https://github.com/monero-integrations/monerowp/blob/2140291ce820673d0cb9b76da76f9e7838b4aa24/monero/include/monero_payments.php#L334)

Take a look at the wpdb docs on [Protecting your Queries](https://codex.wordpress.org/Class_Reference/wpdb#Protect_Queries_Against_SQL_Injection_Attacks) for some tips. 

Thanks for helping bring XMR to the masses!

Gerry

**Comment by serhack** [comment]
Hey,

Oh, a f***ck SQL injection!!! Thanks for reporting the issue! We are working on it now!
Thank you a lot again!

**Comment by serhack** [comment]
The latest commit should fix this issue.

**Comment by cryptochangements34** [comment]
Thank you very much for pointing this out! It should be fixed in PR #33 Please feel free to review it yourself :)
