### ISSUE TITLE
Method not found; Request: {"jsonrpc":"2.0","method":

### ISSUE THREAD

**Issue by NA-Proiv** [monero-integrations/monerowp#34]
Testing API functionality having a few issues. (removed original content) now resolved on the bug issue.

**Comment by serhack** [comment]
Are you sure you are contacting a Wallet rpc? It seems you are trying with a daemon.

**Comment by rkshinde** [comment]
hello, 

We run the ./monerod 

then issue command with ./monero-wallet-rpc  which is running now on the server. I have followed instructions at 
https://github.com/monero-integrations/monerowp/blob/master/README.md

**Comment by WilliamJamesDalrympleWest** [comment]
@serhack  any recommendations?

**Comment by WilliamJamesDalrympleWest** [comment]
@cryptochangements34  and @serhack  any recommendations?

**Comment by serhack** [comment]
Okay, you have run Monero daemon. But Monero Payment gateway needs Monero Wallet Rpc.

So you have to run Monero Wallet Rpc and under settings you have to specify the port and the host where Monero Wallet rpc is. It doesn't seem a bug.

**Comment by cryptochangements34** [comment]
Are you sure that you input the correct port for the monero-wallet-rpc? It sounds like you may have instead given the port for monerod

**Comment by rkshinde** [comment]
Currently we are running below command 

./monero-wallet-rpc --rpc-bind-port 18082 --rpc-login USER:password --log-level 2 --wallet-dir /root/monero-v0.11.1.0/ --daemon-address node.moneroworld.com:1808

**Comment by cryptochangements34** [comment]
@rkshinde the port youre using for node.moneroworld.com is 1808? The correct port is 18089, then once it has sync'd (which can take a while) it should work

**Comment by rkshinde** [comment]
the --daemon-address node.moneroworld.com:1808 was typo by me here , the port used in command is 18089 

@serhack I have already tried it with --wallet-file option I will try  I will try it again

**Comment by rkshinde** [comment]
Still same error as 

Request have return error: Method not found; Request: {"jsonrpc":"2.0","method":"getbalance","params":null,"id":1}; Your balance is: 0 XMR 
Unlocked balance: 0 XMR

**Comment by rkshinde** [comment]
Also Please confirm what settings should be done in plugin, if the port is changed to 18082 then it says can not connect with any host in Monero wallet rpc Host/ IP;  I have used node.moneroworld.com, the localhost IP address and public IP address of the server and the internal IP address of the server

**Comment by serhack** [comment]
If you have Monero Wallet rpc and wp in the same vps , you have to edit Settings 

Monero Wallet rpc host: localhost
Monero Wallet rpc port: 18082

**Comment by WilliamJamesDalrympleWest** [comment]
Ok, no bugs but here is the good one...

46WgbttFnu8RynZph9ET6deNBGYnM22oLbSwE8XikJMnWY2FAPnBC2bXMY99VT8thuMvmRTAtaafvbezk78WkKh6SmC9FgV

Is address entered for testing.

Yet when placing orders 


4GDMchhkQAeRynZph9ET6deNBGYnM22oLbSwE8XikJMnWY2FAPnBC2bXMY99VT8thuMvmRTAtaafvbezk78WkKh6fJ4v5YNzExc9G6JGhe


is being shown front end, now i've tested a few times, and this money is not arriving in FGV but GHE is showing funds / hitting 

Care to explain how this could be happening and where?

**Comment by cryptochangements34** [comment]
@WilliamJamesDalrympleWest this plugin utilizes monero's integrated address system. The address that is shown at check out *is* your address with a payment id "baked in" so that you can keep track of which payment came from which customer

**Comment by WilliamJamesDalrympleWest** [comment]
Ah ok, sorry that makes sense, (we've adapted it for our system away from Woocommerce) but i did not read this on the instructions, ok next question. 

How does one 'load the wallet' as i've got the details but don't appear to have instructions on logging in via SSH (Centos) thanks

**Comment by cryptochangements34** [comment]
@NA-Proiv I'm not sure what you mean by "loading the wallet". If you are talking about getting the monero-wallet-rpc then you need to SSH into your server, install the monero CLI tools from https://getmonero.org then run it with `./monero-wallet-rpc --rpc-bind-port 18082 --disable-rpc-login --log-level 2 --wallet-file /path/walletfile --daemon-address node.moneroworld.com:18089` (the wallet file will typically just be the name of your wallet when you create it with the monero-wallet-cli) then wait for it to sync with the node, which can take even an hour or two depending on your connection. Then you should be able to go to your woocommerce admin panel and specify the port 18082 on localhost.

**Comment by NA-Proiv** [comment]
12-06-2017 @ 16:56:38 - [ERROR] Unable to getting integrated address
12-06-2017 @ 16:57:13 - [ERROR] Unable to getting integrated address
12-06-2017 @ 16:58:18 - [ERROR] Unable to getting integrated address
12-06-2017 @ 16:58:51 - [ERROR] Unable to getting integrated address
12-06-2017 @ 16:59:26 - [ERROR] Unable to getting integrated address
12-06-2017 @ 16:59:59 - [ERROR] Unable to getting integrated address
12-06-2017 @ 17:00:34 - [ERROR] Unable to getting integrated address
12-06-2017 @ 17:01:40 - [ERROR] Unable to getting integrated address
12-06-2017 @ 17:02:15 - [ERROR] Unable to getting integrated address
12-06-2017 @ 17:27:58 - [ERROR] Unable to getting integrated address
12-07-2017 @ 11:09:10 - [ERROR] Unable to getting integrated address
12-07-2017 @ 11:09:54 - [ERROR] Unable to getting integrated address
12-07-2017 @ 11:13:00 - [ERROR] Unable to getting integrated address

**Comment by serhack** [comment]
> ./monero-wallet-rpc --rpc-bind-port 18082 --disable-rpc-login --log-level 2 --wallet-file /path/walletfile --daemon-address node.moneroworld.com:18089

^^ This is the right command. Tell us problems if they appear

**Comment by cryptochangements34** [comment]
@NA-Proiv 
> 12-06-2017 @ 16:56:38 - [ERROR] Unable to getting integrated address
12-06-2017 @ 16:57:13 - [ERROR] Unable to getting integrated address
12-06-2017 @ 16:58:18 - [ERROR] Unable to getting integrated address
12-06-2017 @ 16:58:51 - [ERROR] Unable to getting integrated address
12-06-2017 @ 16:59:26 - [ERROR] Unable to getting integrated address
12-06-2017 @ 16:59:59 - [ERROR] Unable to getting integrated address
12-06-2017 @ 17:00:34 - [ERROR] Unable to getting integrated address
12-06-2017 @ 17:01:40 - [ERROR] Unable to getting integrated address
12-06-2017 @ 17:02:15 - [ERROR] Unable to getting integrated address
12-06-2017 @ 17:27:58 - [ERROR] Unable to getting integrated address
12-07-2017 @ 11:09:10 - [ERROR] Unable to getting integrated address
12-07-2017 @ 11:09:54 - [ERROR] Unable to getting integrated address
12-07-2017 @ 11:13:00 - [ERROR] Unable to getting integrated address

That is from monero-wallet-rpc or a php error?

**Comment by serhack** [comment]
That is Monero Payment Gateway log on Wordpress.

**Comment by cryptochangements34** [comment]
@serhack thanks. That makes more sense

**Comment by serhack** [comment]
Any updates?

**Comment by serhack** [comment]
Closed and marked as support.
