### ISSUE TITLE
Supported Currencies

### ISSUE THREAD

**Issue by cameleater** [monero-integrations/monerowp#58]
WooCommerce shops can support a large variety of currencies however the monero gateway only supports the following:
USD 
EUR
CAD 
INR
GBP 
COP 
SGD 

If the currency of your shop is set to something else in the woocommerce settings then the plugin cannot convert the price total of a customers cart into the amount to pay in XMR.

**Comment by cameleater** [comment]
created a pull request to fix this issue 

https://github.com/monero-integrations/monerowp/pull/59

**Comment by cryptochangements34** [comment]
Thanks for the contribution
