### ISSUE TITLE
Latest code

### ISSUE THREAD

**Issue by kennedybaird** [monero-integrations/monerowp#65]
Hey guys,

Where is the latest code?

The Wordpress plugin has a version of 2.1.1 but this cloned repo shows v 2.0 with SerHack as the author.

**Comment by serhack** [comment]
Hey. This is the latest code. I don't really know why Wordpress has an old version. I'm going to update that too! 

Thanks, SerHack

**Comment by kennedybaird** [comment]
No the WordPress version thinks it has newer code

**Comment by DrCryptoKey** [comment]
Perhaps line 27 in monerowp/monero/include/monero_payments.php needs to be updated from "$this->version = "2.0";" to the current updated version number?

**Comment by kennedybaird** [comment]
Here is the code on my live Wordpress installation, installed via the Wordpress Plugin Installer:

```
<?php
/*
Plugin Name: Monero - WooCommerce Gateway
Plugin URI: https://monerointegrations.com
Description: Extends WooCommerce by Adding the Monero Payment Gateway
Version: 2.1.1
Author: Monero Integrations Team
Author URI: https://monerointegrations.com
*/

// This code isn't for Dark Net Markets, please report them to Authority!
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}
```

Here the code I synced yesterday from this repo:

```
<?php
/*
Plugin Name: Monero - WooCommerce Gateway
Plugin URI: https://monerointegrations.com
Description: Extends WooCommerce by Adding the Monero Gateway
Version: 2.0
Author: SerHack
Author URI: https://monerointegrations.com
*/

// This code isn't for Dark Net Markets, please report them to Authority!
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}
```

**Comment by cryptochangements34** [comment]
The code here at this repo is the latest code. Even though the code you got from wordpress has a higher minor version, it is actually older.

**Comment by kennedybaird** [comment]
What is the process for the code making it from here to WordPress?

On 24/07/2018 11:14 PM, "cryptochangements34" <notifications@github.com>
wrote:

The code here at this repo is the latest code. Even though the code you got
from wordpress has a higher minor version, it is actually older.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/monero-integrations/monerowp/issues/65#issuecomment-407464197>,
or mute the thread

**Comment by cryptochangements34** [comment]
Typically @serhack just takes the code from here and uploads it to wordpress. Idk how they ended up with different versions but it should be corrected soon
