### ISSUE TITLE
Question: CoinMarketCap API Keys?

### ISSUE THREAD

**Issue by irishpride44** [monero-integrations/monerowp#68]
CoinMarketCap is halting their Public API and requiring a API Key to use their calculations (later this year).

https://coinmarketcap.com/api/

"The Public API will be migrating to the new, more powerful Professional API on December 4th, 2018. Please update your application to use the free tier of the Professional API before then. "

**Comment by irishpride44** [comment]
Does that mean plugin needs to be update to support API keys or it doesn't use CoinMarketCap?

**Comment by serhack** [comment]
Hi @irishpride44 ,
This plugin doesn't use CoinMarketCap API.
Thanks,

SerHack
