### ISSUE TITLE
converting price error???

### ISSUE THREAD

**Issue by ghost** [monero-integrations/monerowp#99]
I ran monero wallet rpc with

"monero-wallet-rpc.exe --daemon-address xmr.getmonero.us:18081 --rpc-bind-port 18083 --wallet-file *** --password *** --disable-rpc-login"

and then i installed this plugin and connected to wordpress well.

but when i try to check out sample product, it is displaying

"Payment error:The price for Monero could not be retrieved. Please contact the merchant."

My host OS is window 10 pro. and I tested in MAMP. I would appreciate if you help me.

Have a good day

**Comment by serhack** [comment]
Hi,
thanks for having filled an issue for MoneroWP project. Would you mind if I ask you to check a few things?

* Is cURL enabled?
* Are you able to reach [coingecko-api](https://api.coingecko.com/api/v3/simple/price?ids=monero&vs_currencies=) ?
* Could you please check if there are any problems in writing `monero_gateway_live_rates` table?

That error is given when the price is set to 0. In that particular situation, Woocommerce marks the order as paid by default then I introduced the error to prevent that case.

**Comment by maxqueque** [comment]
cURL is enabled. I can reach coingecko api, There are no problem that table..

**Comment by maxqueque** [comment]
How can I check to reach coingecko-api?? cURL is enabled and It seems that there are no problem in that table.

**Comment by serhack** [comment]
> How can I check to reach coingecko-api?? cURL is enabled and It seems that there are no problem in that table.

If you have direct access (SSH or Telnet) for that machine, you could try to ping Coingecko API (via `ping 104.18.5.127`). Since the service is proxied through Cloudflare, I wonder.. Is the machine on Tor network? Cloudflare can add a captcha or deny any connections from Tor.

If you're on shared hosting (such as GoDaddy, Namecheap and etc..), please note that your hosting provider might have blocked any external connection.

**Comment by maxqueque** [comment]
I've tired that command. I've reached coingecko-api. But still showing "Payment error:The price for Monero could not be retrieved. Please contact the merchant."

**Comment by maxqueque** [comment]
Whenever I check the option 'Show Prices in Monero', products price turn into '0.000000000000 XMR'

**Comment by maxqueque** [comment]
I can reach coingecko-api. But still doesn't work. And whenever I check the option 'Show Prices in Monero', products price turn into '0.000000000000 XMR'.....

Is this a problem because it's not linux or problem with the rpc settings?

**Comment by serhack** [comment]
> I can reach coingecko-api. But still doesn't work. And whenever I check the option 'Show Prices in Monero', products price turn into '0.000000000000 XMR'.....
> 
> Is this a problem because it's not linux or problem with the rpc settings?

It should not be since the payment gateway tries to fetch prices independently of the option chosen in the settings IIRC. I need to dig into this. Could you please check Woocommerce Logs?

**Comment by maxqueque** [comment]
I found the logs : 

`05-31-2021 @ 00:24:08 - [ERROR] Unable to fetch prices from coingecko.com.
05-31-2021 @ 00:25:33 - [ERROR] Unable to fetch prices from coingecko.com.
05-31-2021 @ 00:27:36 - [ERROR] Unable to fetch prices from coingecko.com.
05-31-2021 @ 00:28:30 - [ERROR] Unable to fetch prices from coingecko.com.
05-31-2021 @ 00:28:30 - [ERROR] Impossible to retrieve price for order: 21
05-31-2021 @ 00:29:07 - [ERROR] Unable to fetch prices from coingecko.com.
05-31-2021 @ 00:29:07 - [ERROR] Impossible to retrieve price for order: 21
05-31-2021 @ 00:30:06 - [ERROR] Unable to fetch prices from coingecko.com.
05-31-2021 @ 00:31:00 - [ERROR] Impossible to retrieve price for order: 21
05-31-2021 @ 00:31:06 - [ERROR] Unable to fetch prices from coingecko.com.
05-31-2021 @ 00:32:16 - [ERROR] Unable to fetch prices from coingecko.com.`

**Comment by serhack** [comment]
This error is shown only if the `$price` response is not set. This might happen for many reasons (cURL and JSON extensions must be enabled, CoinGecko API must return something). Excluding Coingecko API and the extensions, I do not know what it could cause that. Is there any particular configuration that you used to install Wordpress and I'm not aware of?

**Comment by maxqueque** [comment]
I set mysql port to 8889. Could this be a problem?

**Comment by maxqueque** [comment]
I found the cause!! I changed mysql port number from 8889 to 3306 and everything was solved!! Please update to improve when using a different mysql port! Thank you!!

**Comment by maxqueque** [comment]
I changed my mysql port(8889 -> 3306) and it was solved!

**Comment by serhack** [comment]
Glad it worked by changing the MySQL port.

**Comment by coffeeguy999** [comment]
> I changed my mysql port(8889 -> 3306) and it was solved!

How did you do this?
